language: node_js
dist: trusty
node_js:
- node
addons:
  chrome: stable
  browserstack:
    username: xuexb1
    access_key:
      secure: J/w5BzoliBGi0g+FsHBmn+aXYk1Q1YOXIECVrKt0ZJGusdN4GNaAS1oAG3Jc53BHa2CsCpCLtk06q21OXNPWADEwYmmbffNlJeQwYniJp4yHSanRg42UiPWhZ/7cWZGHdQGURHv8Np7B4n0wxThGJvk2gZiGwCKbXVeeGXK93NDaqamjKPqBojmeZQz05IvVC9H0xqwaePGyiHp+KASqZfEi2wIHiHLI64/fcJ+KcVVHA/+CmIGHytASOk9KPco+hTbnL/cgMv+HSu9ghP6TSsfXp5FTeLRplOjQ5Sljqstp6mRtRBXxbE1Ajy+H297qYixnfyVo9BC3bZFSkS3+nJAdImIB7HSKxmjGkBmhIdBBBym8/APSLPvalGaPTZjVqEbxcpEKkx4jQVXEPhefxAmRFrEXwS6VATScRlRNoloUrpXQV7sQ8GZWhVjUCYXf6CLcRCOagEL6uPZ3gW99Dpk5fhzGpcc01vR+Aq8g7xvUUnI4kKgknAUgDlviXOqYGORQPqs2WUCURFBrkyfKWUsIm7GRo2Wxif4S+t5sJJT3J/Qu96IB62ArEZZ0KhfTkHDqPp8+LbVGlklHtXtYYU0kpROO4b7JfzJNOBtGSL2p6ROyYBdjaZztvgW1QO/LKGxAMvXfWyERyahwnEclPULz23LV0FFM9nSU9tsJeT0=
  jwt:
    secure: EYFprl/MblgFbMfbHANjptjxFa8JAC+Cf5GHeLIvtgbM7Ou/QfdhT3uiNTnUIh48pTbrBOdYRQC6tQ4u2If8/bp2PUfRnf9cLtOKywxIQVuGES3o/6LPicKPh1uwtyYrGEl85KtgdWjO8W6E2UU9V32Ou66DRanzMJMIUS/0ewDy3GEa0nJM/V72i5oQxJzZUBuFHiUN2H4zPhGZdBcv2XdXhDr239bT+KOTi2H891SlY7j2Dtz5Ul1ugfrRLyBhfcsdTpY2yqOkczPIuppCYdZ802809A3lNOfBdfomRruPIWbgcsPD8vFTKtUNTnFDYHISS00uY+JwPJrJPxiUwDEcNxvsjsyjNCUAUXYtlvRJKWRZwr0Rk3FmbINkQWVnoK1X9FP+EQSojQH1DzexG4Mri7Xh5N+yhOzV73Lcn9UrBP44IKaGbV6pr5g/a9xtiJQMx3PXhZU/HmRuhQH5rlZyYfqf33ZbRwtTEuOOg3RnGayx3kqZc7+X/xb+lJBd5rtoTnjWI7JafRyrqwzLT4O7CpspRse5nvGE9hWw61NDgRV3LT8jy5fkyUMLmC3+rO23B+sw8bnqdWn25wfoGyDToXZhH7PGm69J8Jv1uK4hHsfj9UJZbEuoqrCYc3EYO7A6Ax2VgQYX4zUz9JTSLZuYbaChQb0rEga6xBq1KYQ=
env:
  global:
  - BROWSER_STACK_USERNAME: xuexb1
sudo: false
cache:
  directories: node_modules
script:
- npm run test:cov
- npm run test:sauce
after_script: npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
